name: cut new release

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for update
        id: version_check
        run: |
          if ./scripts/check-for-update.sh; then
            echo "update_available=true" >> "$GITHUB_OUTPUT"
          else
            echo "update_available=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Update formula
        if: steps.version_check.outputs.update_available == 'true'
        run: |
          ./scripts/archive-current-formula.sh
          ./scripts/update.sh > Formula/fe.rb
          git config --global user.email "github-actions-bot@example.com"
          git config --global user.name "GitHub Actions Bot"
          git add .
          git commit -m "Added new Release via GitHub Actions"
          git push origin main
