name: cut new release

on:
  schedule:
    - cron:  '*/10 * * * *'
  pull_request:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run first script
        run: |
          ./scripts/check-for-update.sh
        id: version_check
        continue-on-error: true  # This allows the workflow to continue even if the script fails
      - name: Run second script if the versions differ
        if: steps.version_check.outcome == 'failure'
        run: |
          ./scripts/archive-current-formula.sh
          ./scripts/update.sh > Formula/fe.rb
          git config --global user.email "github-actions-bot@example.com"
          git config --global user.name "GitHub Actions Bot"
          git checkout -b testbranch2
          git add .
          git commit -m "Automatic commit via GitHub Actions"
          git push origin testbranch2  # Replace with the desired branch